#!/usr/bin/env bash
# Convert the world layers to PDF for the World module, and size the app icon.
#
# Design/world/*.svg is the source of truth (2340×844 world). Do not hand-edit the PNGs — they are
# generated, and committed so that a build never depends on rsvg-convert being installed.
# Needs rsvg-convert: brew install librsvg
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v rsvg-convert >/dev/null; then
  echo "rsvg-convert not found. brew install librsvg" >&2
  exit 1
fi

# The v2 Ink & Ember world: four layers (sky, far, mid, near) in three palettes (day, gold, dusk),
# generated by Design/ink/generator/build.py. Every layer ships as PDF and WorldArt rasterises it
# at runtime at the resolution its depth needs, so nothing here depends on a device size. The v2
# art has no raster filters, so the twelve PDFs come to under half a megabyte.
world="HopTalesPackage/Sources/World/Resources"
mkdir -p "$world"
rm -f "$world"/*.pdf "$world"/*.png
for source in Design/ink/world/*.svg; do
  name=$(basename "$source" .svg)
  rsvg-convert -f pdf "$source" -o "$world/$name.pdf"
  echo "rendered $name ($(du -h "$world/$name.pdf" | cut -f1))"
done

# The app icon. Its source is a raster rather than an SVG, so it is resized with sips rather than
# rasterised. Unlike the world layers this PNG is committed: CI never runs this script, and a build
# without an icon is refused by App Store Connect.
icon=HopTales/Assets.xcassets/AppIcon.appiconset
mkdir -p "$icon"
sips -s format png -z 1024 1024 Design/icon.png --out "$icon/icon-1024.png" >/dev/null
cat > "$icon/Contents.json" <<'JSON'
{
  "images" : [
    { "filename" : "icon-1024.png", "idiom" : "universal", "platform" : "ios", "size" : "1024x1024" }
  ],
  "info" : { "author" : "xcode", "version" : 1 }
}
JSON
echo "rendered app icon"
